### ISSUE TITLE
docs: HTTP 404 Digital Asset Exchange Read The Docs

### ISSUE THREAD

**Issue by petermetz** [hyperledger-archives/sawtooth-docs-archive#91]
Go here:
https://sawtooth.hyperledger.org/examples/marketplace.html

Then click on `Read the Docs` which will take you to here (dead):
https://intelledger.github.io/0.7/mktnav_users_guide.html

**Comment by mtbc** [comment]
Perhaps this isn't still an issue? The site seems to have changed enough I'm not now managing to track this down.

**Comment by petermetz** [comment]
@mtbc I can no longer locate the same link/menu item on the main docs page either, e.g. the original page (`/examples/marketplace.html`) that contained the dead link now appears non-existent so we could close this as having been fixed in the scope of some other change/fix in the meantime that I wasn't aware of!
